### PR TITLE
Improved reading of en_us.json & changing death.attack.paperCut

### PR DESCRIPTION
**Pull request by TheDirectorX**
Everything is taken from the file `en_us.json` `1.15.2`
* Sorted for a better view
* Changed `death.attack.paperCut` message. I hope you will like it.

I push to the `1.14.4` **branch** because in `1.15.2` files and folders are not in their places.

### CODE REVIEW

**Comment by MelanX** [comment]
There are no Ender, Fiery, Nether, Prismarine and Slime Tools in 1.14.4, they are only implemented in 1.15.2. The new description for paper is ok.
But I don’t see why I should use this.. it’s as readable as before, just sorted alphabetically 🤔

**Comment by TheDirectorX** [comment]
Sorting was done for `1.15.2`. It is visually more pleasant and convenient to look when the types of tools are separated. This will be convenient for other translators. I just thought the items from `1.15.2` and `1.14.4` would be the same.

**Comment by MelanX** [comment]
No problem :) But if I would use this file, it will be overwritten from the data generator and looks like before.
I'm thinking about let translations be in the default directory because writing the java code could be complicated... And if I add more stuff, it will have names like "null".
Because of that, you can make a PR for the default directory. (assets/morevanillatools/lang/)

**Comment by TheDirectorX** [comment]
Simply, generated json doesn't have a more convenient visual look.
**On the left** is what I propose. **On the right** is what is in the file `morevanillatools-1.15.2-2.0.jar`:
image
Although this is a small thing, it will obviously be easier for translators. This is exactly what I came across when I started making translation.

**Pull request closed without merging**
